local host = assert(_G._host, "native host api is not registered")

-- lr 用于逐步兼容懒人精灵。
-- 当前只映射已经由底层实现的基础能力；完整兼容要按文档逐项补齐。
local lr = {
    print = host.print,
    sleep = host.sleep,
    tap = host.touch.tap,
    swipe = host.touch.swipe,
    inputText = host.input.text,
    pasteText = host.input.pasteText,
    pressKey = host.key.press,
    back = host.key.back,
    home = host.key.home,
    isRootAvailable = host.device.isRootAvailable,
    screenState = host.device.screenState,
    wakeDevice = host.device.wake,
    sleepDevice = host.device.sleep,
    battery = host.device.battery,
    rotation = host.device.rotation,
    setRotation = host.device.setRotation,
    getSetting = host.device.settings.get,
    putSetting = host.device.settings.put,
    deleteSetting = host.device.settings.delete,
    getProp = host.device.prop.get,
    setProp = host.device.prop.set,
    displayInfo = host.device.display.info,
    setDisplaySize = host.device.display.setSize,
    resetDisplaySize = host.device.display.resetSize,
    setDisplayDensity = host.device.display.setDensity,
    resetDisplayDensity = host.device.display.resetDensity,
    setBrightness = host.device.display.setBrightness,
    setAutoBrightness = host.device.display.setAutoBrightness,
    rootExec = host.root.exec,
    rootStatus = host.root.status,
    rootStat = host.root.file.stat,
    rootList = host.root.file.list,
    rootChown = host.root.file.chown,
    rootPidOf = host.root.process.pidOf,
    rootProcessList = host.root.process.list,
    rootProcessInfo = host.root.process.info,
    rootProcessStats = host.root.process.stats,
    rootKill = host.root.process.kill,
    runApp = host.app.open,
    closeApp = host.app.stop,
    clearAppData = host.app.clearData,
    grantAppPermission = host.app.grant,
    revokeAppPermission = host.app.revoke,
    currentApp = host.app.current,
    installApp = host.app.install,
    uninstallApp = host.app.uninstall,
    disableApp = host.app.disable,
    enableApp = host.app.enable,
    disableAppComponent = host.app.disableComponent,
    enableAppComponent = host.app.enableComponent,
    isAppInstalled = host.app.isInstalled,
    capture = host.screen.capture,
    getPixel = host.image.getPixel,
    getPixels = host.image.getPixels,
    releaseImage = host.image.release,
}

lr.__compat = {
    name = "lazy",
    status = "partial",
}

_G.lr = lr
